#!/bin/bash

if [ "$(uname)" == 'Darwin' ]; then
  fswatch -e '^\./(\.git|work|\.venv|temp)|__pycache__|\.tmp' -r ./ | python script/watch.py
else
  inotifywait -e close_write --exclude '^\./(\.git|work|\.venv|temp|\.mypy_cache)|__pycache__|\.tmp' -m -r ./ | python script/watch.py
fi
