#!/bin/bash -eu

package_lambda () {
  local -r side="$1"
  local -r flow="$2"
  local -r cwd="$(pwd)"
  local -r src="$cwd/src/$side-$flow"
  local -r dest="$cwd/work/$side-$flow"
  local -r zip="$cwd/work/$side-$flow.zip"

  rm -fr "$zip"
  mkdir -p "$dest"
  rsync -r --delete --exclude=__pycache__ \
    "$src/.venv/lib/python3.11/site-packages/" "$dest"
  rsync -r --exclude=__pycache__ --exclude=.venv --exclude='test_*.py' \
    "$src/" "$dest"

  cd "$dest"
  local -r digest="$(find . -type f -exec md5sum {} \; | sort -k 2 | md5sum | cut -f1 -d' ')"
  cd "$cwd"

  local -r alt_zip="$cwd/work/development/$side-$flow.$digest.zip"

  cd "$dest"
  zip -q -r "$zip" .
  cd "$cwd"

  cp "$zip" "$alt_zip"
}

mkdir -p work/development/
rm -f work/development/*

package_lambda origin request
package_lambda origin response
