#!/bin/bash -eux

package_lambda () {
  local -r dest=work/imglambda

  rm -fr work/imglambda.zip "$dest"
  mkdir -p "$dest"
  rsync -r --delete \
    --exclude=__pycache__ \
    --exclude='test_*.py' \
    --exclude=/pip \
    --exclude='/pip-*' \
    work/release-venv/.venv/lib/python3.13/site-packages/ \
    index.py \
    VERSION \
    imglambda \
    "$dest"

  pushd "$dest"
  local -r digest="$(find . -type f -exec md5sum {} \; | sort -k 2 | md5sum | cut -f1 -d' ')"
  zip -q -r ../imglambda.zip .
  popd

  cp work/imglambda.zip "work/development/imglambda.$digest.zip"
}

mkdir -p work/development/
rm -f work/development/*

package_lambda
