#!/bin/bash -eu

export AWS_ACCESS_KEY_ID="$(< config/development/access-key-id)"
export AWS_SECRET_ACCESS_KEY="$(< config/development/secret-access-key)"

s3_bucket="$(< config/development/s3-bucket)"
s3_key_prefix="$(< config/development/s3-key-prefix)"

ls work/development | xargs -I{} aws s3 cp "work/development/{}" "s3://$s3_bucket/$s3_key_prefix{}"
